[[feeds]]
name = "stocks-in-action"
url = "https://www.marketsmojo.com/news/stocks-in-action"
title = "MarketsMojo â€“ Stocks in Action (Custom RSS)"
description = "Unofficial feed generated via Feed me up, Scotty!"
